### ISSUE TITLE
Custom color implementation

### ISSUE THREAD

**Issue by chriswallace** [ChurchThemes-WP/shepherd-theme#21]
I was planning to implement custom colors the same way we normally do, but I'm wondering if this theme could use a simpler approach.

The way Twenty Fifteen works is that it basically adds custom color controls to the customizer and allows uber-fast previews of the custom colors, making it much easier to work with for users. The underlying magic can be [seen here](https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentyfifteen/inc/customizer.php) where there is a handlebars-style template that they pass arguments into through the customizer. There is also a [Javascript component](https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentyfifteen/js/color-scheme-control.js) that helps with rendering this all live. 

I would like to implement our custom colors in Shepherd Pro the same way, since I don't see a huge need for dynamic text color with this theme.

**Comment by garand** [comment]
@chriswallace Should we just delegate this functionality to [Colorcase](https://github.com/UpThemes/Colorcase), like you mentioned [here](https://github.com/UpThemes/creative-theme/pull/69#issuecomment-68554940)?

**Comment by angela-crist** [comment]
@garand @chriswallace Let me know what we want to do here.

**Comment by garand** [comment]
I say delegate to [UpThemes/Colorcase](https://github.com/UpThemes/Colorcase), but not sure if this is still even relevant.

**Comment by angela-crist** [comment]
I will close out, @chriswallace please reopen if you feel otherwise
